### ISSUE TITLE
Do edges really need ids.

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/lsif-node#13]
Edges are used to connect to vertices but don't need to be identified separately.

**Comment by BertanAygun** [comment]
I noticed this is a fairly old issue but wanted to comment still, while I agree we don't technically need edge ids they have been useful for diagnosis. Although we can also use line numbers (or sequence numbers) for such purpose.

**Comment by dbaeumer** [comment]
I agree with @BertanAygun argument. They are useful for error message and I think their overhead in the dump is not too big. DBs can still decide to store them differently.
