### ISSUE TITLE
Query: how it connects to language server

### ISSUE THREAD

**Issue by mgupta0421** [microsoft/lsif-node#130]
The file protocol.ts at line 6 says it connects with language server 'vscode-languageserver-protocol,' but the doubt is we create the dump.lsif file with CLI command, so how does it connect to the specific language server. For example, the client sends all its capabilities while requesting a language server, and in response, the server does the same, so where or how all that communication happening?

**Comment by dbaeumer** [comment]
It uses the same data types as the LSP protocol (e.g. hover, ...)

**Comment by mgupta0421** [comment]
how does 'lsif-node' as a client connect to 'vscode-languageserver-protocol' server (eg. initialize request, ..)?. Where I can find the code where 'lsif-node-protocol' sends the request to 'vscode-languageserver-protocol' server.
