### ISSUE TITLE
Add support for default exports

### ISSUE THREAD

**Issue by arjunattam** [microsoft/lsif-node#30]
Consider the following minimal project:

**exporter.ts**
```ts
export default function() {
    return 5;
}
```

**index.ts**
```ts
import five from './exporter'

function main() {
    five();
}
```

Currently, the `referenceResult` for `five` points to the 2 references in index.ts, skipping the default export reference defined in exporter.ts.

**Comment by dbaeumer** [comment]
This got addressed in version 0.5.x
