### ISSUE TITLE
LSIF TSC emitter high resource usage

### ISSUE THREAD

**Issue by mostafaeweda** [microsoft/lsif-node#36]
I've run the TSC emitter on https://github.com/Microsoft/vscode/ and it aborted with a V8 out-of-memory error when giving it a 4GB memory limit:
```
node --max-old-space-size=4096 ~/Code/lsif-node/tsc/bin/lsif-tsc -p tsconfig.json --projectRoot /Users/most/Code/vscode/src/ > vscode.lsif
```

However, it worked when I gave it `8GB` limit.

Is that expected for a project of this size? what about really big projects?

The same applies for CPU usage: both TypeScript and TSC emitter use one thread/process (low utilization) and spend a long time to output `lsif` (console progress would be nice).

I wonder how would that work for big projects?

**Comment by dbaeumer** [comment]
The memory usage is IMO OK. The code can't be compiled with 4GB of memory either and the LSIF tooling can't do better than the compiler.

When the output is written to a file the tool now prints progress to the console. 

I will close the issue.
