### ISSUE TITLE
resultSet not connected to any edge

### ISSUE THREAD

**Issue by jumattos** [microsoft/lsif-node#38]
Steps to reproduce:
1. Clone and install [lsif-util](https://github.com/jumattos/lsif-util)
2. `lsif-tsc -p .\tsconfig.json | node .\lib\main.js validate --stdin`

The above line should validate the LSIF output of the lsif-tsc tool using the lsif-util itself as the repository to index.

13/452 (roughly 3%) of the resultSet vertices are not connected to any edge. This is likely a bug that should be investigated.

**Comment by dbaeumer** [comment]
Ran it today and it passed. Closing.
