### ISSUE TITLE
Moniker for Generics / things without a declaration

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/lsif-node#41]
There are use cases where we need monikers for things that necessarily don't have a declaration. An example is C# where when hovering of List<string> the hover refers to List<string> and not to List<T>. To share the hover between all usages of List<string> we need to have either a declaration for List<string> or at least a result set.

**Comment by dbaeumer** [comment]
How for example instantiated generics are treated might be different from LS to LS. The TS language server for example doesn’t make any different between List<string> and List<number>. If you hover over either of those they show the same doc and the same signature List<T>. However I see that other language servers do different (for example C#). I would not go down the road of having monikers on all references for this. I would rather do the following:

1. Have a direct link from the range to the result. In the above example the range representing List<string> can have a direct `textDocument/hover` edge to the special hover. In addition it can have a `refersTo` edge to the result set of List<T> to reuse the results shared across all type instantiations of List<T>. Downside is that this might introduce a lot of LSP request specific edges instead of having one refersTo edge.
1. We generate a virtual document for List<string> for example which give us a declaration range we can link a moniker too. But this looks like a bad work around.
1. We allow having a result set without a declaration range. The spec currently allows this, however you can’t have a moniker associated with it. 

I am in favor of 3.) For the spec I would do the following:

- A moniker can be bound to a declaration range
- A moniker can also be bound to a result set but only if there is no declaration range or no moniker is attached to the declaration range. I don’t want to end up in a situation where the moniker between a declaration range and the result set differs since it would be hard to explain what the semantic of this is.

As said earlier I don’t want to force exporters to always emit result sets since this might not be convenient in all cases. So we still need to be able to handle the case that there is no result set. Performance wise that shouldn’t make a difference since in both cases getting the moniker evolves the equal amount of lookups."

**Comment by LukaszMendakiewicz** [comment]
Note the two messages above got the angle brackets and text between stripped, losing the arguments for generics in the result.

**Comment by dbaeumer** [comment]
@LukaszMendakiewicz thanks for pointing this out. I fixed the comment.

**Comment by dbaeumer** [comment]
I added a corresponding sentence to the spec.

**Comment by dbaeumer** [comment]
However please see also https://github.com/microsoft/lsif-node/issues/42#issuecomment-510127062

**Comment by dbaeumer** [comment]
In 0.5.0 monikers are supported on Range, ResultSet, DeclarationResult, DefinitionResult, TypeDefinitionResult, ReferenceResult, ImplementationResult.

I will close the issue. If we have a concrete use case that this is not sufficient we need to look into solving it.
