### ISSUE TITLE
Moniker placement - range vs resultset 

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/lsif-node#42]
The reason for this is currently that the ResultSet vertex is optional and considered an optimization. A LSIF output that directly links from a range to a hover result using the `textDocument/hover` edge is perfect valid as well. I am reluctant on forcing everybody to emit a ResultSet however I fully acknowledge that a moniker can not be emitted late to implement the partitioning optimization. Alternatively we can say that a moniker can only be emitted if there is a ResultSet. But not sure if this is too restrictive as well.

**Comment by dbaeumer** [comment]
From @LukaszMendakiewicz I am +1 on moniker on result set. For us, result set is basically represent 1 symbol decl.

**Comment by dbaeumer** [comment]
So I would propose that we allow monikers on result sets. However to make things consistent with other definition in LSIF this moniker is considered if the range pointing to the result set doesn't have its own moniker.

**Comment by dbaeumer** [comment]
So for the spec I would do:

- A moniker can be bound to a declaration range
- A moniker can also be bound to a result set but it is only considered if the range pointing to the result set has no moniker or there is not a range at all. 

This makes it consistent on how we deal with LSP specific edges. If the range has one the one of the range is taken. If it doesn't we look for a corresponding result set and a LSP specific edge there.

**Comment by LukaszMendakiewicz** [comment]
3 responses up the quote attributed to me is actually HeeJae's. I did however fully agree with it, saying:
> For my implementation I pretty much map a “symbol” 1:1 with a result set (even if we go partitioned by document the general idea stays the same), so it is very natural to me to have the moniker linked or inlined in the result set.

**Comment by dbaeumer** [comment]
@LukaszMendakiewicz not sure I understand your latest comment. The proposal fully supports mapping a symbol 1:1 to a result set. However it also allows for a different implementation where this is not the case (as we do for example for all LSP request specific edges which can be bound to a range as well).

**Comment by LukaszMendakiewicz** [comment]
I did not disagree with the proposal. I was just clarifying that the comment you attributed to me few messages above was actually HeeJae's, but that I also did agree with it.

**Comment by dbaeumer** [comment]
While trying to formalize this for the spec and noticed that it is not enough to say monikers can go onto declaration ranges. They need to go on all ranges which raises the following question:

- can the same moniker be attached to n ranges / result sets. 

From my pint of view there is nothing that should prohibit this. Opinions?

**Comment by LukaszMendakiewicz** [comment]
I do not see a reason against that -- that sounds like plain deduplication.

However I would also like to ensure it is specified so that the deduplication is not a requirement.
I.e. if:

> ResultSet1 links to Moniker1 with identifier FooBar
> ResultSet2 links to Moniker2 with identifier FooBar

it is equivalent to:

> Both ResultSet1 and ResultSet2 link to Moniker1 with identifier FooBar

**Comment by dbaeumer** [comment]
I can agree on that.

**Comment by dbaeumer** [comment]
In 0.5.0 monikers are supported on Range, ResultSet, DeclarationResult, DefinitionResult, TypeDefinitionResult, ReferenceResult, ImplementationResult.

I will close the issue. If we have a concrete use case that this is not sufficient we need to look into solving it.
