### ISSUE TITLE
How to efficiently reach a moniker

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/lsif-node#43]
I see the need for this. Possible options:

1. Assuming that we implement moniker mappings we could think about inlining the moniker as a value object into the declaration range / result set as an optional property.
1. We spec that before a request specific edge (e.g. textDocument/* ) can be emitted for a range / result set the corresponding moniker must be emitted if available. This makes sure that the DB imported knows the moniker before any request specific result comes.
1. We move the whole format away from a vertex / edge model more to an embedded Id model (relational model). So a range or result set would have a monikerId. This way we force that the moniker is emitted before the range / result set

I am actually in favor of 1. or 2. Three gets IMO complicated with something like ranges. We would need to hold back the document until all ranges are known since we would need to reference them from a contains property in the document. I am the opinion that such a model will complicate writing these exporters.

**Comment by dbaeumer** [comment]
From @LukaszMendakiewicz 

1 and 2 both make sense to me.

Pros of 2: Less redundant data (moniker vertex can be reused for may ranges/resultSets

**Comment by BertanAygun** [comment]
I like #2 and I am more inclined to placing monikers on result set as well. While I am aware they are optional, if we don't have them I am concerned about the cost of finding the moniker for a range.

If my understanding is correct, without resultsets and where moniker is linked in declaration range only, I would have to:
1) For any range, wait for declarationResult edge.
2) Query previous entries for declerationResult range
3) Follow the moniker edge

Doing #1 and #2 repeatedly for all ranges can be quite expensive, I would imagine I would use an in-memory cache of declerationResult -> moniker table to speed things up.

I think this is one case where a slight verbosity in LSIF (ie resultSet in between range -> declarationResult) can help with processing LSIF output greatly.

**Comment by dbaeumer** [comment]
@BertanAygun will it help if we say: if there is a result set it must carry the moniker. This would give you always a constant distance from a result (e.g. declarationResult) to the moniker.

**Comment by BertanAygun** [comment]
That sounds reasonable, so does it mean that resultSet will inline the moniker vertex id?

**Comment by dbaeumer** [comment]
I added this to the 0.4.0 spec, but a moniker is still linked using an edge to make this consistent with all other edges.
