### ISSUE TITLE
Do monikers need to be either export or import

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/lsif-node#44]
From @LukaszMendakiewicz 

Is it actually required to differentiate between export and import monikers, or could export/import be just an optional property on a generic moniker vertex, for languages where this information is available unambiguously?

In C++ in general case there is not a specific syntax to export or import a symbol (think libs, not DLLs), so any declaration may be either – I only know that in link time based on the fact whether given project provided a definition (then it is exporting) or not (then it is importing). So 1) I would need to defer providing this information until I finish processing the entire project, and 2) I will never be able to tell whether a moniker is importing intentionally or by mistake (because the user forgot to provide a definition).

Additionally for certain code elements like inline functions (defined in a header) or types there really is no a single domicile project – they are neither exported nor imported in any, they are just one definition common to all. (Note that a header file may legally, and commonly is, not included in project file).

**Comment by dbaeumer** [comment]
May be some background on why this is in the spec right now. For languages that `link` against declaration files it is helpful to know if that moniker on a declaration imports the symbol into the project or exports it. Otherwise this interpretation has to be done on the URI which would be hard to do in a generic way. Let me make an example:

- dependency on mbox (which is written in JS)
- dev dependency on @types/mbox to get the typings.

The dev dependency bring a lot of *.d.ts files which basically declare the API of mbox and therefore introduce a lot of declaration ranges (they declare a symbol). Lets assume one is `npm:mbox:Foo`.

If you now do a FAR reference search for `npm:mbox:Foo` you will find all these declarations which in fact a references to the symbol. To be able to detect that I added the `MonikerKind`. 

Checking the URI might even not work in all cases since a symbol defined in JS but declared using TS will still show up in a `d.ts` file. In this case it will be an exported symbol.

**Comment by LukaszMendakiewicz** [comment]
> If you now do a FAR reference search for npm:mbox:Foo you will find all these declarations which in fact a references to the symbol. To be able to detect that I added the MonikerKind.

Am I correct to infer that then FAR is expected to omit results `MonikerKind` = `import`?

I don't think my suggestion conflicts with your need: making `kind` field in `Moniker` optional will still allow to express the JS/TS dichotomy, but will reduce burden on languages for which the import/export concept is not as clearly defined.

**Comment by dbaeumer** [comment]
> Am I correct to infer that then FAR is expected to omit results MonikerKind = import?

Only that declaration. The references inside that project to that declaration should be part of the FAR.

> I don't think my suggestion conflicts with your need: making kind field in Moniker optional will still allow to express the JS/TS dichotomy, but will reduce burden on languages for which the import/export concept is not as clearly defined.

Agree, it could be optional. I will update the spec if this is OK for everyone.

**Comment by dbaeumer** [comment]
The kind is optional since 0.5.0 (https://github.com/microsoft/lsif-node/blob/master/protocol/src/protocol.ts#L533)
