### ISSUE TITLE
"scheme" or "schema"

### ISSUE THREAD

**Issue by LukaszMendakiewicz** [microsoft/lsif-node#47]
The protocol uses both the term "scheme":

> The **scheme** of the moniker. For example tsc or .Net
> **scheme**: string;

and "schema":

> **schema** owners are allowed to define the structure if they want.

I *think* the intended term here is "schema", so I suggest the protocol is adjusted to use that as the name of the field while it is still early and can be changed without breaking too many customers.

**Comment by dbaeumer** [comment]
I named it `scheme` to be in line with URIs where this is named `scheme` and not `schema`. But I am open to name it either way.

**Comment by LukaszMendakiewicz** [comment]
That's a good rationale. Changing "schema" to "scheme" in the other usage is also easier since it's just in a comment.

**Comment by dbaeumer** [comment]
OK. Then we go with `scheme`
