### ISSUE TITLE
Allowing equal ranges

### ISSUE THREAD

**Issue by LukaszMendakiewicz** [microsoft/lsif-node#48]
The current specification states:

>The ranges emitted for a document must follow these rules:
> No two ranges can be equal.

This is problematic for tagged ranges which may want to have multiple kinds of tags at the same location due to preprocessing of the source code.

Consider the following C++ example:
```cpp
#define M int x;
M
```

The second line is both a reference to `M` but also a definition of `x`.
What would be the right way to express this with tagged ranges?
Should it be tagged just as a reference to `M` because the definition of `x` is not visible in the code?

**Comment by LukaszMendakiewicz** [comment]
Maybe such implicit locations (`x` definition) could be expressed with 0-length ranges, and the restriction of not equality have exclusion for 0-length ranges? I'm thinking this might be possible because 0-length ranges would not be used for other operations (e.g. hover) as they would be "invisible" in the client/editor.

**Comment by dbaeumer** [comment]
I would not allow equal ranges of length > 0 because this makes it very hard to decided which range to pick. In general I am open to say that we can have zero length ranges and that they should be ignored when resolving positions to ranges.

For the above example however I would say this is not necessary. I would store this as follows:

```c++
#define M int x;
```

Have two ranges one covering `M` one `int x` with a result set.

For line 
```
M
```

add a reference result item edge for the result set of `M` and a definition item edge for the result set of `int X`

But I am not sure if this is feasible for all C macro expansion constructs.

**Comment by LukaszMendakiewicz** [comment]
I see what you are saying for the simple example, but I think that logic will not express general constructs well, e.g. consider a small modification to:
```c++
#define M(name) int name;
M(x)
M(y)
```
At this point, it would not make sense to add a range/result set for "int name" since it is not a construct that will be referred to later; it will just be used to synthesize "int x" in line 2 and "int y" in line 3, which each will have its own result set.

So are you then leaning to allow overlapping 0-length ranges?

A simple example where there would be multiple at the same location of them would be:
```c++
#define M(name) int name##1; int name##2;
M(x)
M(y)
```
which, for clarity, during compilation transforms to:
```c++
 
int x1; int x2;
int y1; int y2;
```
Pertinent LSIF output would roughly be:
```json
{"id":8,"type":"vertex","label":"range","start":{"line":1,"character":0},"end":{"line":1,"character":1},"tag":{"type":"reference"}}
{"id":12,"type":"vertex","label":"range","start":{"line":1,"character":0},"end":{"line":1,"character":0},"tag":{"type":"definition"}}
{"id":18,"type":"vertex","label":"range","start":{"line":1,"character":0},"end":{"line":1,"character":0},"tag":{"type":"definition"}}
{"id":21,"type":"vertex","label":"range","start":{"line":2,"character":0},"end":{"line":2,"character":1},"tag":{"type":"reference"}}
{"id":25,"type":"vertex","label":"range","start":{"line":2,"character":0},"end":{"line":2,"character":0},"tag":{"type":"definition"}}
{"id":31,"type":"vertex","label":"range","start":{"line":2,"character":0},"end":{"line":2,"character":0},"tag":{"type":"definition"}}
```
where:
  * 8 and 21 are the reference ranges for result set for macro "M"
  * 12 is the definition range for `x1`
  * 18 is the definition range for `x2`
  * 25 is the definition range for `y1`
  * 31 is the definition range for `y2`

An alternative to this approach would be to dismiss vertices 12, 18, 25, and 31, and instead use the ranges for the macros (8 and 21) as the result ranges for definitions of `x1`, `x2`, `y1`, and `y2`.
The downside here would be though that the tag on such resulting range will not be accurately describing its content and may be difficult to process for some tools consuming the LSIF.

**Comment by LukaszMendakiewicz** [comment]
I see the philosophical difference between the two approaches is how we interpret ranges.

If the ranges describe the visible code as the user sees in the editor, then 0-length ranges does not make much sense.

If the range describe the results of LSP operations, then 0-length ranges are appropriate:
> Where is the definition of `x1`?
> Here with zero-length because it is not visible in code.

My interpretation was that LSIF goal is to express the latter.

**Comment by dbaeumer** [comment]
I was thinking about this again and using zero length ranges here is actually not the right thing to do. Reason being is that you actually want to point to `M(x)` as the definition of `x` and not to the beginning. However that whole region is not sensitive for a LSP request operation. I see two approaches:

1. these ranges are stored as LSP locations. This is already supported in the protocol. But this has the downside that we need to embed the URI into every LSP location which is very unpleasant.
2. we allow to tag ranges as not being mouse sensitive. E.g. they can not be used as a starting ranges for a LSP request.

I am actually in favor of (2). For sensitive ranges we would still require the rules of none overlapping and non equal.

**Comment by LukaszMendakiewicz** [comment]
(2) makes sense to me too.

That would be expressed as another property on the range vertex, like `"resultOnly":true`. The property would be `false` by default (if omitted).

Thus the example above could be encoded as:
```json
{"id":8,"type":"vertex","label":"range","start":{"line":1,"character":0},"end":{"line":1,"character":1},"tag":{"type":"reference"}}
{"id":12,"type":"vertex","label":"range","start":{"line":1,"character":0},"end":{"line":1,"character":4},"tag":{"type":"definition"},"resultOnly":true}
{"id":18,"type":"vertex","label":"range","start":{"line":1,"character":0},"end":{"line":1,"character":4},"tag":{"type":"definition"},"resultOnly":true}
{"id":21,"type":"vertex","label":"range","start":{"line":2,"character":0},"end":{"line":2,"character":1},"tag":{"type":"reference"}}
{"id":25,"type":"vertex","label":"range","start":{"line":2,"character":0},"end":{"line":2,"character":4},"tag":{"type":"definition"},"resultOnly":true}
{"id":31,"type":"vertex","label":"range","start":{"line":2,"character":0},"end":{"line":2,"character":4},"tag":{"type":"definition"},"resultOnly":true}
```

Additionally 12 and 18, and 25 and 31 could be deduplicated with each other, but that would be optional - up to the exporter to decide.

So is this a consensus and the spec is going to be updated with that?

**Comment by dbaeumer** [comment]
Yes, I would add that to the spec with one difference: I would propose to have a different vertex label `resultRange` to make the difference more clear. Such a range will not have a tag either.

**Comment by LukaszMendakiewicz** [comment]
Why not keep `tag` optional for `resultRange` vertex? For a use case I can imagine tools that want to show all definitions in a given document, even if the names are defined in macro expansions; such tools may even have some nice UI to differentiate visible (`range`) and invisible (`resultRange`) definitions.

**Comment by dbaeumer** [comment]
Keeping it optional is actually a good idea.

**Comment by dbaeumer** [comment]
Added to the spec.
