### ISSUE TITLE
[lsif-util] Tool skips thorough validation

### ISSUE THREAD

**Issue by arjun27** [microsoft/lsif-node#51]
I'm trying to run the validation tool on stdin, and I see a message saying "skipping thorough validation" because `lsif-protocol` is not found in the global node modules location. Is this expected? It would be nice if the `lsif-util` tool could install `lsif-protocol` as a dependency if it is one.

```
➜ node out/index.js | lsif-util validate --stdin
Reading input... done
Skipping thorough validation: /Users/arjun/.nvm/versions/node/v9.11.1/node_modules/lsif-protocol/lib/protocol.d.ts was not found
...
```

//cc @jumattos

**Comment by arjun27** [comment]
Just to test exhaustively, I tried installing `lsif-protocol` globally, but the tool is still unable to locate the `protocol.d.ts` file. This is because the location that is being looked for is different from my package installation location.

Location checked: `/Users/arjun/.nvm/versions/node/v9.11.1/node_modules/lsif-protocol/lib/protocol.d.ts`

Actual location (extra `lib`): `/Users/arjun/.nvm/versions/node/v9.11.1/lib/node_modules/lsif-protocol/lib/protocol.d.ts`

The actual location can also be verified by running `npm root -g`

**Comment by jumattos** [comment]
Ops! I've seem this issue before, and it is supposed to be fixed. I am sorry you had to encounter it.

Which version of `lsif-util` are you using?

**Comment by jumattos** [comment]
`lsif-protocol` is a dependency of `lsif-util`. At run-time, we check which folder the global `lsif-util` is installed in and look for the corresponding `node_modules/lsif-protocol`. I don't know why the extra `lib`, but I will investigate. Thanks for reporting!

**Comment by arjun27** [comment]
Thanks! I'm using v0.1.3 of lsif-util.

If the tool is looking for lsif-protocol in the node_modules of the installed lsif-util, then the location on my setup would be: `/Users/arjun/.nvm/versions/node/v9.11.1/lib/node_modules/lsif-util/node_modules/lsif-protocol/lib/protocol.d.ts`

However, the location that is being searched for is: `/Users/arjun/.nvm/versions/node/v9.11.1/node_modules/lsif-protocol/lib/protocol.d.ts`

**Comment by jumattos** [comment]
That's strange. I am also using version 0.1.3. I would not expect `node_modules` to be under `lib`.

What's your OS? I wonder if that could explain the difference.

**Comment by arjun27** [comment]
Thanks for the pointer. I tried digging into the source, with installations on this machine (macOS - Node setup with [nvm](https://github.com/nvm-sh/nvm)) and Windows (basic Node setup), and found an issue. In both cases, I had installed v0.1.3 using `npm install -g lsif-util`

In [this line](https://github.com/microsoft/lsif-node/blob/master/util/src/main.ts#L60), we use `process.argv[1]` to find the location of the lsif-util installation. This returns different values on the 2 machines

* macOS: `/Users/arjun/.nvm/versions/node/v9.11.1/bin/lsif-util`
* Windows: `C:\Users\arattam\AppData\Roaming\npm\node_modules\lsif-util\bin\lsif-util`

Notice that the path on Windows is inside the lsif-util installation path (not the case for macOS)

Instead of `process.argv[1]` did we explore using `__filename` or `__dirname`? Using `__filename` returns the same result on both machines (`.../lsif-util/lib/main.js`) and seems like a better fit (assuming it doesn't break anything else)
