### ISSUE TITLE
Missing Implementation Results

### ISSUE THREAD

**Issue by jumattos** [microsoft/lsif-node#80]
**Implementation results are not being generated on the latest version (0.4.10).**

### Reproducing steps

For the following code snippet:

``` typescript
interface MyInterface {
    foo(): void;
}

class MyClass implements MyInterface {
    public foo(): void {
        console.log("foo");
    }
}
```
This is the LSIF generated: ([complete results here](https://github.com/microsoft/lsif-node/files/3817168/lsif.txt))

#### Range
``` json
{
   "id":9,
   "type":"vertex",
   "label":"range",
   "start":{
      "line":0,
      "character":10
   },
   "end":{
      "line":0,
      "character":21
   },
   "tag":{
      "type":"definition",
      "text":"MyInterface",
      "kind":11,
      "fullRange":{
         "start":{
            "line":0,
            "character":0
         },
         "end":{
            "line":2,
            "character":1
         }
      }
   }
}
```

#### Result Set
``` json
{
   "id":6,
   "type":"vertex",
   "label":"resultSet"
}
```

#### Moniker
``` json
{
   "id":7,
   "type":"vertex",
   "label":"moniker",
   "kind":"local",
   "scheme":"tsc",
   "identifier":"S5xaJxo6Y0OyPGBg0uENEg=="
}
```

#### Outgoing edges from result set
``` json
{
   "id":8,
   "type":"edge",
   "label":"moniker",
   "outV":6,
   "inV":7
},
{
   "id":12,
   "type":"edge",
   "label":"textDocument/hover",
   "outV":6,
   "inV":11
},
{
   "id":59,
   "type":"edge",
   "label":"textDocument/definition",
   "outV":6,
   "inV":58
},
{
   "id":62,
   "type":"edge",
   "label":"textDocument/references",
   "outV":6,
   "inV":61
}
```

#### Graph

![bug](https://user-images.githubusercontent.com/45983213/68346331-b76b7500-00a8-11ea-8c5a-41fa8aa80b12.png)

**As you can see, there is no "textDocument/implementation" edge coming out of either the moniker or the result set. In fact, there are no implementation edges at all.**

**Comment by jumattos** [comment]
Quicker way to verify the problem:

> lsif-tsc -p .\tsconfig.json --stdout | Select-String textDocument/implementation

**Comment by jumattos** [comment]
@dbaeumer Can you take a look at this?

**Comment by dbaeumer** [comment]
Will close the issue for now since LSIF didn't have recent activity.
